"""
Dynamic Agent Creator - Creates new agents on the fly
"""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.user import Agent, ModelProvider
from app.schemas.schemas import AgentCreate


class AgentCreator:
    """Creates new agents dynamically based on workflow needs"""
    
    def __init__(self, db: AsyncSession, user_id: int):
        self.db = db
        self.user_id = user_id
    
    async def create_agent_from_spec(self, spec: dict) -> Agent:
        """
        Create a new agent from a specification
        spec example:
        {
            "name": "Web Scraper",
            "role": "Website content extractor",
            "goal": "Scrape and extract content from websites",
            "tools": ["web_search"],
            "model_provider": "groq",
            "model_name": "llama3-8b-8192"
        }
        """
        # Check if agent with same name already exists
        result = await self.db.execute(
            select(Agent).where(
                Agent.owner_id == self.user_id,
                Agent.name == spec["name"],
                Agent.status == "active"
            )
        )
        existing = result.scalar_one_or_none()
        if existing:
            return existing
        
        # Create new agent
        agent = Agent(
            owner_id=self.user_id,
            name=spec.get("name", "Generated Agent"),
            role=spec.get("role", "AI Assistant"),
            goal=spec.get("goal", "Help users with tasks"),
            backstory=spec.get("backstory", "Generated by AI Workflow Planner"),
            instructions=spec.get("instructions", ""),
            model_provider=ModelProvider(spec.get("model_provider", "groq")),
            model_name=spec.get("model_name", "llama3-8b-8192"),
            temperature=spec.get("temperature", 0.1),
            max_tokens=spec.get("max_tokens", 1024),
            tools=spec.get("tools", []),
            is_public=False,
        )
        
        self.db.add(agent)
        await self.db.flush()
        await self.db.refresh(agent)
        
        return agent